# Generated by Django 3.2.16 on 2023-02-17 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videolink', models.CharField(blank=True, max_length=250, null=True)),
                ('youtubelink', models.CharField(blank=True, max_length=250, null=True)),
                ('dateupload', models.DateField(default=datetime.datetime.now)),
                ('tag', models.CharField(blank=True, max_length=250, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdetails.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Contentmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, max_length=1, null=True)),
                ('media_name', models.CharField(blank=True, max_length=100, null=True)),
                ('media_path', models.CharField(blank=True, max_length=200, null=True)),
                ('media_image', models.ImageField(upload_to='images/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channels.channel')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdetails.userdetail')),
            ],
        ),
    ]
