# Generated by Django 3.2.16 on 2023-02-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
