# Generated by Django 3.2.16 on 2023-02-20 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='dateupload',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
