# Generated by Django 3.2.16 on 2023-02-17 05:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_status', models.BooleanField(default=False)),
                ('credit_card', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=30)),
                ('facebook_ac', models.CharField(blank=True, max_length=30)),
                ('ig_ac', models.CharField(blank=True, max_length=200)),
                ('linkedin_ac', models.CharField(blank=True, max_length=200)),
                ('patreon_ac', models.CharField(blank=True, max_length=200)),
                ('pinterest_ac', models.CharField(blank=True, max_length=200)),
                ('youtube_ac', models.CharField(blank=True, max_length=200)),
                ('twitter_ac', models.CharField(blank=True, max_length=200)),
                ('user_icon', models.ImageField(blank=True, upload_to='photos/users/%Y/%m/%d')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('active', 'active'), ('banned', 'banned')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
