# Generated by Django 3.2.16 on 2023-02-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
